### PR TITLE
fix: Broken Search Links

### LINKED ISSUE #51: broken links in search
image

### PR DESCRIPTION
**Pull request by alishaz-polymath**
Adds metadata based search result omission to remove redirect links from appearing on search results

Fixes #51

### CODE REVIEW

File: components/common-alt/search/index.jsx [hunk 1]
```diff
@@ -7,14 +7,16 @@ import { removeFileExtension } from "@utils/files"
 import Link from "next/link"
 
 export const SearchResult = ({ result, selected, onMouseOver, onClick }) => {
+  const url = result.path.replace("\\index","");
```
Comment (alishaz-polymath) [inline components/common-alt/search/index.jsx:10]: This is essential because the search results from Fuse.js results the path /index for folders whereas the folder pages loads up without the index in the URL. This sorts it out.

File: components/common-alt/search/index.jsx [hunk 2]
```diff
@@ -246,6 +249,12 @@ export const getDescription = (file) => {
     || file.meta?.meta?.["og:description"]
 }
 
+export const getOmitFromSearch = (file) => {
+  return file.meta?.omitFromSearch
+    || file.meta?.meta?.omitFromSearch
+    || file.meta?.meta?.["og:omitFromSearch"]
+}
```
Comment (alishaz-polymath) [inline components/common-alt/search/index.jsx:256]: Omit from search using metadata

File: components/common-alt/search/index.jsx [hunk 3]
```diff
@@ -196,7 +199,7 @@ export const Search = ({ data, limit = 5, placeholder, indexKeys = ['title', 'de
 
   const search = useCallback((value) => {
     const fuseResult = fuseRef.current.search(value)
-    dispatch({ type: 'SET_RESULTS', results: fuseResult.map(r => r.item) })
+    dispatch({ type: 'SET_RESULTS', results: fuseResult.map(r => r.item).filter(item => !item.omitFromSearch) })
```
Comment (alishaz-polymath) [inline components/common-alt/search/index.jsx:202]: Filter out when omitFromSearch is true

File: pages/core-features/embed/install-with-react.mdx [hunk 4]
```diff
@@ -1,3 +1,7 @@
+---
+omitFromSearch: true
+---
```
Comment (alishaz-polymath) [inline pages/core-features/embed/install-with-react.mdx:3]: This is how we pass omitFromSearch in metadata inside .mdx or .mdoc files
